University/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace University.Controllers
{
    [Route("")]
    public class HomeController : Controller
    {
        public HomeController()
        {
        }

        [Route("")]
        [Route("Index")]
        [Route("Home")]
        public IActionResult Index() => View();

        [Route("Privacy")]
        public IActionResult Privacy() => View();
    }
}

University/Controllers/PassportController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Logging;
using University.Communication;
using University.Database.Models;
using University.ViewModels;
using System.Security.Claims;

namespace University.Controllers
{
    /// <summary>
    /// Котроллер паспорта.
    /// Здесь находятся страницы и методы для управления аутентификацией, регистрацией, восстановления доступа и т.д.
    /// </summary>
    [Authorize]
    [Route("[controller]/[action]")]
    public class PassportController : Controller
    {
        private readonly UserManager<User> m_UserManager;
        private readonly SignInManager<User> m_SignInManager;
        private readonly ILogger m_Logger;
        private readonly IEmailSender m_EmailSender;

        private Dictionary<string, ErrorModelRoute> m_ErrorModelRoutes = new Dictionary<string, ErrorModelRoute>
        {
            { "DuplicateEmail", new ErrorModelRoute { key = "Email", message = "Такой email уже зарегистрирован" } },
            { "InvalidEmail", new ErrorModelRoute { key = "Email", message = "Неверный email" } }
        };

        private struct ErrorModelRoute
        {
            public string key;
            public string message;
        }

        public PassportController(
            UserManager<User> userManager,
            SignInManager<User> signInManager,
            IEmailSender emailSender,
            ILogger<PassportController> logger)
        {
            m_UserManager = userManager;
            m_SignInManager = signInManager;
            m_EmailSender = emailSender;
            m_Logger = logger;
        }

        /// Страницы авторизации.
        /// Методы представляющие механизмы авторизации в системе.
        /// За исключением внутренней системы авторизации 
        /// так-же здесь находятся механизмы для авторизации через стороннии сервися
        #region Login methods

        /// <summary>
        /// Страница входа в систему.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Login(string returnUrl = null)
        {
            // Очищаем существующие внешние куки для валидного процесса входа
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

            WriteReturnUrl(returnUrl);
            return View();
        }

        /// <summary>
        /// Метод процесса авторизации на сайте.
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(PassportLoginViewModel model, string returnUrl = null)
        {
            WriteReturnUrl(returnUrl);
            if (ModelState.IsValid)
            {
                var user = await m_UserManager.FindByEmailAsync(model.Email);
                if (user == null)
                {
                    ModelState.AddModelError(string.Empty, "Логин или пароль неверны");
                    return View(model);
                }

                var result = await m_SignInManager.PasswordSignInAsync(user, model.Password, true, lockoutOnFailure: true);

                if (result.Succeeded)
                {
                    m_Logger.LogInformation("User logged in.");
                    return RedirectToLocal(returnUrl);
                }

                if (result.IsLockedOut)
                {
                    m_Logger.LogWarning("User account locked out.");
                    return RedirectToAction(nameof(Lockout));
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Логин или пароль неверны");
                    return View(model);
                }
            }

            // Что-то пошло не так, возвращаем страницу авторизации
            return View(model);
        }

        #endregion

        /// Страницы аутентификации через внешние источники.
        #region External authentication pages

        /// <summary>
        /// Метод запрос аутентификации у стороннего ресурса
        /// </summary>
        /// <param name="provider"></param>
        /// <param name="returnUrl"></param>
        /// <returns></returns>
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public IActionResult ExternalLogin(string provider, string returnUrl = null)
        {
            // Запрос редиректа на стороннюю аутентификацию.
            var redirectUrl = Url.Action(nameof(ExternalLoginCallback), GetControllerRouteName(), new { returnUrl });
            /// var redirectUrl = "/passport/oauth2callback";
            var properties = m_SignInManager.ConfigureExternalAuthenticationProperties(provider, redirectUrl);
            return Challenge(properties, provider);
        }

        [HttpGet]
        [AllowAnonymous]
        ///[Route("/signin-google")]
        ///[Route("/signin-vkontakte")]
        public async Task<IActionResult> ExternalLoginCallback(string returnUrl = null, string remoteError = null)
        {
            if (remoteError != null)
            {
                return RedirectToLogin();
            }

            var info = await m_SignInManager.GetExternalLoginInfoAsync();
            if (info == null)
            {
                return RedirectToLogin();
            }

            // Вход для зарегистрированного пользователя по внешним параметрам входа
            var result = await m_SignInManager.ExternalLoginSignInAsync(info.LoginProvider, info.ProviderKey, isPersistent: false, bypassTwoFactor: true);
            if (result.Succeeded)
            {
                m_Logger.LogInformation($"User logged in with {info.LoginProvider} provider.");
                return RedirectToLocal(returnUrl);
            }

            if (result.IsLockedOut)
            {
                return RedirectToLockout();
            }
            else
            {
                // Если у пользователя нет аккаунта, то спрашиваем его о создании аккаунта на основе внешних данных.
                ViewData["ReturnUrl"] = returnUrl;
                ViewData["LoginProvider"] = info.LoginProvider;
                
                return View("ExternalLogin", new PassportExternalLoginViewModel
                {
                    Email = info.Principal.FindFirstValue(ClaimTypes.Email),
                    FirstName = info.Principal.FindFirstValue(ClaimTypes.GivenName),
                    LastName = info.Principal.FindFirstValue(ClaimTypes.Surname)
                });
            }
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ExternalLoginConfirmation(PassportExternalLoginViewModel model, string returnUrl = null)
        {
            if (ModelState.IsValid)
            {
                // Получение информации о пользователи по данным из внешнего источника.
                var info = await m_SignInManager.GetExternalLoginInfoAsync();
                if (info == null)
                {
                    throw new ApplicationException("Error loading external login information during confirmation.");
                }

                var user = Database.Models.User.CreateNewUser();
                user.Email = model.Email;
                user.UserFirstName = model.FirstName;
                user.UserMiddleName = model.MiddleName;
                user.UserLastName = model.LastName;
                
                var result = await m_UserManager.CreateAsync(user);
                if (result.Succeeded)
                {
                    result = await m_UserManager.AddLoginAsync(user, info);
                    if (result.Succeeded)
                    {
                        await m_SignInManager.SignInAsync(user, isPersistent: true);
                        m_Logger.LogInformation("User created an account using {Name} provider.", info.LoginProvider);
                        return await SendEmailConfirmationAndRedirectToEmailConfirmation(user);
                    }
                }

                AddErrors(result);
            }

            ViewData["ReturnUrl"] = returnUrl;
            return View(nameof(ExternalLogin), model);
        }

        #endregion

        /// Страницы регистрации.
        /// Методы представляющие механизмы регистрации в системе.
        #region Registration

        /// <summary>
        /// Страница регистрации нового аккаунта.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [AllowAnonymous]
        public IActionResult Register(string returnUrl = null)
        {
            WriteReturnUrl(returnUrl);
            return View();
        }

        /// <summary>
        /// Метод процесса регистрации нового аккаунта
        /// </summary>
        /// <param name="model"></param>
        /// <param name="returnUrl"></param>
        /// <returns></returns>
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(PassportRegisterViewModel model, string returnUrl = null)
        {
            WriteReturnUrl(returnUrl);
            if (ModelState.IsValid)
            {
                var user = Database.Models.User.CreateNewUser();
                user.Email = model.Email;
                user.UserFirstName = model.FirstName;
                user.UserMiddleName = model.MiddleName;
                user.UserLastName = model.LastName;

                var result = await m_UserManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    m_Logger.LogInformation("User created a new account with password.");

University/Controllers/ScheduleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using University.Authorization;
using University.Database;
using University.ViewModels;

namespace University.Controllers
{
    ///[Authorize(Policy = PolicyConstants.PolicyManagers)]
    [Route("[controller]/[action]")]
    public class ScheduleController : Controller
    {
        private readonly ILogger m_Logger;
        private readonly StudentGroupManager m_StudentGroupManager;
        private readonly InstructorManager m_InstructorManager;
        private readonly ScheduleConfiguration m_ScheduleConfiguration;

        public ScheduleController(
            ILogger<ScheduleController> logger,
            StudentGroupManager studentGroupManager,
            InstructorManager instructorManager,
            ScheduleConfiguration scheduleConfiguration)
        {
            m_Logger = logger;
            m_StudentGroupManager = studentGroupManager;
            m_InstructorManager = instructorManager;
            m_ScheduleConfiguration = scheduleConfiguration;
        }

        [Route("")]
        [Route("/[controller]/")]
        public async Task<IActionResult> Index()
        {
            var model = new SchedulePageDisplayViewModel(
                await m_StudentGroupManager.Repository.GetAsync(),
                await m_InstructorManager.Repository.GetAsync(),
                m_ScheduleConfiguration);
            return View(model);
        }
    }
}

University/Views/Home/HomeLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>University</title>

    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&amp;subset=cyrillic" rel="stylesheet">

    <link type="text/css" rel="stylesheet" href="~/stylesheets/home.min.css" asp-append-version="true" />
    <link type="text/css" rel="stylesheet" href="~/stylesheets/webapp.min.css" asp-append-version="true" />
    <link type="text/css" rel="stylesheet" href="~/stylesheets/layouts.min.css" asp-append-version="true" />
    <link type="text/css" rel="stylesheet" href="~/fonts/material-icons.css" asp-append-version="true" />

    <script src="~/scripts/main.js" asp-append-version="true"></script>
    <script src="~/scripts/utils.js" asp-append-version="true"></script>
    <script src="~/scripts/layouts.js" asp-append-version="true"></script>
    <script src="~/scripts/navigation.js" asp-append-version="true"></script>
</head>
<body>
    <div id="root" class="webapplication-root-content">
        @await Html.PartialAsync("_Topbar")
        <div class="webapplication-section webapplication-content modern-scrollbar">
            @RenderBody()
        </div>
    </div>
</body>
</html>

University/Views/Home/Index.cshtml
@{
    Layout = "HomeLayout";
    ViewBag.Title = "Домашняя страница";
}

<div class="webapp-body-content-root">
    <section class="webapp-body-nav-section" id="home-navigation">
        <div class="webapp-nav-group">
            <div class="webapp-nav-group-header">Основное</div>
            <a class="webapp-nav-link disable-link" href="/">
                <i class="icon material-icon">home</i>
                <span>Главная страница</span>
            </a>
            <a class="webapp-nav-link disable-link" asp-controller="Schedule" asp-action="Index">
                <i class="icon material-icon">developer_board</i>
                <span>Расписание</span>
            </a>
        </div>
        <div class="webapp-nav-group">
            <div class="webapp-nav-group-header">Администрирование</div>
            <a class="webapp-nav-link disable-link" asp-controller="Dashboard" asp-action="Index">
                <i class="icon material-icon">insert_chart</i>
                <span>Панель управления</span>
            </a>
        </div>
        <div class="webapp-nav-group">
            <div class="webapp-nav-group-header">Аккаунт</div>
            <a class="webapp-nav-link disable-link" asp-controller="Passport" asp-action="Login">
                <i class="icon material-icon">account_box</i>
                <span>Авторизация</span>
            </a>
            <a class="webapp-nav-link disable-link" asp-controller="Home" asp-action="Privacy">
                <i class="icon material-icon">security</i>
                <span>Конфиденциальность</span>
            </a>
        </div>
    </section>
    <section class="webapp-body-content-section">
        <div class="webapp-size-min-content-fixed">
            <div class="webapp-content-box">
                <div class="home-welcome-box-image"></div>
                <div class="home-welcome-box-content">
                    <div class="home-welcome-box-content-header">Добро пожаловать</div>
                    <div class="home-welcome-box-content-info">
                        <span>Ресурс является демонстрационной версией сайта дипломного проекта</span>
                        <span class="marker">Разработка web-сервиса "расписание в вузе"</span>
                        <div class="home-welcome-box-content-developer">
                            <b>Разработчик:</b>
                            <a target="_blank" href="https://vk.com/id223351289">Медведев А.В.</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="webapp-content-box" style="background: #36a1ed">
                <div class="webapp-content-box-normal-content" style="color: #fff">
                    <div class="webapp-content-box-demo-icon material-icon" style="color: #fff; padding: 20px 0 35px 0">verified_user</div>
                    <div>
                        <b>Для получения доступа к панели управления запростие e-mail и пароль у администратора сайта</b>
                    </div>
                </div>
            </div>
            <div class="webapp-content-box" style="background: #ee9453">
                <div class="webapp-content-box-normal-content" style="color: #fff; text-shadow: 2px 2px 3px rgba(0, 0, 0, .2)">
                    <div>
                        <b>Web-сервис сожержит тестовое расписание и не является достоверным источником расписания вуза</b>
                    </div>
                </div>
            </div>
            @Html.Partial("_Footer")
        </div>
    </section>
</div>
<script type="text/javascript">
        window.navigation.createMenuAutoHandlerForLink(document.getElementById("home-navigation"), "webapp-nav-link", "webapp-nav-link-active");
</script>